### ISSUE TITLE
CSP block connection to GraphQL API on www subdomain

### ISSUE THREAD

**Issue by b0oml** [CyberPlanning/webclient#12]
When using cyberplanning on subdomain www ([https://www.cyberplanning.fr/](https://www.cyberplanning.fr/)), the web client can't connect to [https://www.cyberplanning.fr/graphql/](https://www.cyberplanning.fr/graphql/) due to a CSP issue.

![](https://i.ibb.co/hKQQ9Jq/issue-csp.png)

**Comment by Hedroed** [comment]
Fixed
