### ISSUE TITLE
Alignement du mois

### ISSUE THREAD

**Issue by DocBlack89** [CyberPlanning/webclient#5]
Le nom du mois n'est pas bien centré. 
![image](https://user-images.githubusercontent.com/22809438/53806581-9a950580-3f4d-11e9-8434-70b83ebdd423.png)

**Comment by Hedroed** [comment]
Bonjour déjà,

Je ne comprend pas le mois est bien centré dans sa zone.

**Comment by Hedroed** [comment]
It's a feature

**Comment by b0oml** [comment]
Yes but it's pas bo

**Comment by DocBlack89** [comment]
C'est pas centré par rapport à l'écran. Et ce n'est pas une feature. Stop troll.

**Comment by Hedroed** [comment]
Ok, can you propose a solution please? :fuelpump:
You have 1 month
